### PR TITLE
Recommend service(8) instead of init.d-scripts

### PR DESCRIPTION
**Pull request by ptman**
service should call systemd and upstart controlled services when appropriate

### CODE REVIEW

**Comment by mikemaccana** [comment]
Thanks for the PR. A couple of quick questions:
 - Is service Ubuntu-added or is it in upstream in Debian?
 - Do the official Ubuntu docs use 'service' or the initscripts?

**Comment by ptman** [comment]
It's in redhat, centos, ubuntu, debian. Probably comes from LSB. Depends on the age of the ubuntu documentation. Old ones are /etc/init.d, then comes service wrapping init.d, then service for upstart, then systemctl (which service will also call).

**Comment by mikemaccana** [comment]
Indeed, however we have a policy of preferring 'official' mechanisms to do something where possible. Red Hat's official docs now use systemd directly, eg:

https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7-Beta/html/System_Administrators_Guide/sect-Managing_Services_with_systemd-Services.html

Do the Ubuntu docs use 'service' or call the init scripts directly?

**Comment by ptman** [comment]
I have no idea what the relvant Ubuntu documentation might be. Here's something that mentions service as the 'new' way: https://help.ubuntu.com/community/UbuntuBootupHowto

**Comment by carlwgeorge** [comment]
`service` is a shell script that varies greatly between distributions.  On older Red Hat systems (RHEL 5/6) it is used for calling SysVinit scripts in `/etc/init.d`.  On newer systemd-based Red Hat systems (Fedora, RHEL 7), it is primarily a wrapper for `/usr/bin/systemctl`, with some checks for legacy scripts in `/etc/init.d`.  On Ubuntu, it is primarily a wrapper for `/sbin/initctl` (or symlinks to it such as `/sbin/start` and `/sbin/stop`), with legacy fallback to SysVinit scripts in `/etc/init.d`.

This situation gets even more complex when you consider the fact that many systems make heavy use of their non-primary init system.  For example, RHEL 6 is primarily considered a SysVinit system, but the core boot process is Upstart.  On one of my RHEL 6 servers I found **38** SysVinit scripts and **14** Upstart jobs.  Ubuntu primarily uses Upstart, but on an example 14.04 server I found **37** SysVinit scripts to go along with **87** Upstart jobs.

The best bet is to stick with whatever is recommended by official documentation, as @mikemaccana pointed out.  I haven't verified myself, but I imagine for Ubuntu that is going to be the initctl symlinks (`/sbin/start`, `/sbin/stop`, etc).

**Comment by mikemaccana** [comment]
`service` is OK for Ubuntu - see official Ubuntu docs: https://help.ubuntu.com/lts/serverguide/dns-configuration.html

**Comment by mikemaccana** [comment]
Will publish updated version soon.

**Pull request merged**
